# Generated by Django 6.1.1 on 2026-10-06 08:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('barbers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('payment_id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_date', models.DateField(auto_now_add=True)),
                ('payment_status', models.CharField(choices=[('SU', 'Success'), ('FA', 'Failed')], max_length=2)),
                ('razorpay_transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('barber_id', models.ForeignKey(db_column='barber_id', on_delete=django.db.models.deletion.CASCADE, to='barbers.barber')),
            ],
        ),
    ]
