# Generated by Django 6.1.1 on 2026-10-08 06:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('barbers', '0002_alter_barber_subscription_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('payment_id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_date', models.DateField(auto_now_add=True)),
                ('payment_status', models.CharField(choices=[('created', 'Created'), ('authorized', 'Authorized'), ('success', 'Success'), ('failed', 'Failed'), ('refunded', 'Refunded')], max_length=25)),
                ('razorpay_transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('barber_id', models.ForeignKey(db_column='barber_id', on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='barbers.barber')),
            ],
        ),
    ]
