# Generated by Django 5.2.17 on 2026-09-30 04:51

import barbers.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Barber',
            fields=[
                ('barber_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('account_created_at', models.DateTimeField(auto_now_add=True)),
                ('location', models.JSONField(blank=True, null=True)),
                ('subscription_status', models.CharField(default='trial', max_length=20)),
                ('subscription_expiry_date', models.DateField(default=barbers.models.default_expiry)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='barber', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
