# Generated by Django 5.2.17 on 2026-09-29 07:34

import barbers.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Barber',
            fields=[
                ('barber_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('contact_number', models.CharField(max_length=20)),
                ('account_created_at', models.DateTimeField(auto_now_add=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('subscription_status', models.CharField(default='trial', max_length=20)),
                ('subscription_expiry_date', models.DateField(default=barbers.models.default_expiry)),
            ],
        ),
    ]
