# Generated by Django 5.2.17 on 2026-10-05 05:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('barbers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('slot_id', models.AutoField(primary_key=True, serialize=False)),
                ('slot_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('status', models.CharField(choices=[('available', 'Available'), ('na', 'Not available'), ('booked', 'Booked (customer pending approval)'), ('approved', 'Approved')], default='available', max_length=20)),
                ('barber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='barbers.barber')),
            ],
            options={
                'ordering': ['start_time'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('booking_id', models.AutoField(primary_key=True, serialize=False)),
                ('booking_status', models.CharField(default='waiting', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('barber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='barbers.barber')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL)),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='bookings.slot')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='slot',
            index=models.Index(fields=['barber', 'slot_date'], name='bookings_sl_barber__dc04ca_idx'),
        ),
        migrations.AddConstraint(
            model_name='slot',
            constraint=models.UniqueConstraint(fields=('barber', 'slot_date', 'start_time'), name='unique_barber_slot'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['barber', 'slot'], name='bookings_bo_barber__0291ff_idx'),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.UniqueConstraint(condition=models.Q(('booking_status__in', ['waiting', 'approved'])), fields=('slot',), name='one_active_booking_per_slot'),
        ),
    ]
